library(tidycensus)
library(tidyverse)
library(sp)
library(sf)
library(languageserver)
#library(httpgd)
library(doBy)
library(ipumsr)
library(data.table)
library(writexl)
library(wesanderson)
library(tidyxl)
library(readxl)
library(treemap)
library(viridis)
library(httr2)
library(jsonlite)
library(readxl)
library(readr)
library(terra)
library(maptiles)
library(MetBrewer)
library(purrr)
library(stringr)
library(lubridate)
library(scales)
library(fixest)
library(arrow)
library(matrixStats)


add.alpha
add.alpha <- function(col, alpha=1){
  if(missing(col))
    stop("Please provide a vector of colours.")
  apply(sapply(col, col2rgb)/255, 2, 
        function(x) 
          rgb(x[1], x[2], x[3], alpha=alpha))  
}	
